# Generated by Django 4.2.2 on 2023-07-01 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stackbase', '0005_alter_comment_content_alter_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.ManyToManyField(related_name='question_post_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
